dataset:
    preload: false
    
    video_dir: 'processed_data/subset_instruments/video/'
    spec_dir: 'processed_data/subset_instruments/spec/'
    audio_dir: 'processed_data/subset_instruments/audio/'

    video_ext: '.mp4'
    spec_ext: '.flac'
    audio_ext: '.flac'
    