eval:
    device: 'cpu'
    batch_size: 16

    load_ckpt: false
    load_ckpt_path: 'ckpt/00050000.pt'

    subset_config_path:
        - 'config/subset/instruments.yaml'
        - 'config/subset/pets.yaml'
        - 'config/subset/speech.yaml'


model:
    video:
        num_segments: 15
        n_div: 8
    spec:
        # sample_rate needs to be changed to 16000
        sample_rate: 16000
        window_size_ms: 0.025
        hop_size_ms: 0.010
        mel_bins: 64
        fmin: 50
        fmax: 14000
    audio:
        sample_rate: 16000
        
    feature_dim: 2048
    hidden_dim: 512
    emb_dim: 128
