train:
    device: 'cuda'
    lr: 0.0002
    warmup_step: 500
    max_step: 40000
    batch_size: 32
    num_workers: 4
    fp16: false
    wandb: true
    wandb_exp_name: 'debug_converge'
    debug: true

model:
    video:
        num_segments: 15
        n_div: 8
    spec:
        sample_rate: 32000
        window_size_ms: 0.025
        hop_size_ms: 0.010
        mel_bins: 64
        fmin: 50
        fmax: 14000
    audio:
        sample_rate: 32000
        
    feature_dim: 2048
    hidden_dim: 512
    emb_dim: 128

dataset:
    preload: false
    
    video_dir: 'processed_data/video/'
    spec_dir: 'processed_data/spec/'
    audio_dir: 'processed_data/audio/'
    # video_dir: 'old_processed/video/'
    # spec_dir: 'old_processed/spec/'
    # audio_dir: 'old_processed/audio/'
    
    video_ext: '.mp4'
    spec_ext: '.flac'
    audio_ext: '.flac'
    