train:
    device: 'cpu'
    epoch: 1
    lr: 0.001
    warmup_step: 5000
    max_step: 400000
    batch_size: 2
    num_workers: 0
    
model:
    video:
        num_segments: 15
        n_div: 8
    spec:
        sample_rate: 32000
        window_size_ms: 0.025
        hop_size_ms: 0.010
        mel_bins: 64
        fmin: 50
        fmax: 14000
    audio:
        sample_rate: 32000
        
    feature_dim: 2048
    hidden_dim: 512
    emb_dim: 128

dataset:
    video_dir: 'processed/video/'
    spec_dir: 'processed/spectrogram/'
    audio_dir: 'processed/audio/'
    
    video_ext: '.mp4'
    spec_ext: '.flac'
    audio_ext: '.flac'
    